field: e567b6ab-3855-452b-a337-4c119dac4d62 # Body Content
fieldLayouts:
  e25f5116-982d-45a0-ac12-9d3a3f1d07e7:
    tabs:
      -
        elements:
          -
            fieldUid: a6ca7d80-fa7f-433b-b6ba-fd9f19791f82 # Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a69ee201-bae7-41da-b168-e8845101b16f
            warning: null
            width: 100
          -
            fieldUid: 09c265f3-2ab1-405d-9111-108e6b54f0fb # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1e542aa-e800-4112-9f5f-2879d509f3a7
            warning: null
            width: 100
          -
            fieldUid: 5fd465cf-5b00-4b4f-8ee0-ce0eac4fd2eb # Attribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e6ca961-e740-4d10-a151-c04cb84e8716
            warning: null
            width: 100
        name: Content
        uid: c82ef1c7-6d7a-42db-a18d-0048b2893a90
fields:
  5fd465cf-5b00-4b4f-8ee0-ce0eac4fd2eb: # Attribution
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: attribution
    instructions: ''
    name: Attribution
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  09c265f3-2ab1-405d-9111-108e6b54f0fb: # Quote
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  a6ca7d80-fa7f-433b-b6ba-fd9f19791f82: # Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: ''
    name: Style
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Blockquote
            -
              - value
              - blockquote
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Pullquote
            -
              - value
              - pullquote
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: quote
name: Quote
sortOrder: 2
