field: e567b6ab-3855-452b-a337-4c119dac4d62 # Body Content
fieldLayouts:
  59ffc94b-a1a3-4ecb-98e4-67dbd4317f23:
    tabs:
      -
        elements:
          -
            fieldUid: df3a27ff-e318-422f-8ff5-d626eda8ce54 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d321fb9-6f23-4b85-b389-6571b6f3a8a9
            warning: null
            width: 100
        name: Content
        uid: a8feaa26-e7b8-4ec8-9601-d54ec3f46b29
fields:
  df3a27ff-e318-422f-8ff5-d626eda8ce54: # Rich Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: ''
    name: 'Rich Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richText
name: 'Rich Text'
sortOrder: 1
