dateModified: 1569444785
email:
  fromEmail: sam@craftcms.com
  fromName: 'Craft Blog'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  911477c7-3c92-407b-a9a9-e69ccb74eabb:
    name: Common
fields:
  031e8547-9981-4367-ad27-178240517ea1:
    name: 'Site Introduction'
    handle: siteIntroduction
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\redactor\Field
    settings:
      redactorConfig: ''
      purifierConfig: ''
      cleanupHtml: true
      removeInlineStyles: '1'
      removeEmptyTags: '1'
      removeNbsp: '1'
      purifyHtml: '1'
      columnType: text
      availableVolumes: '*'
      availableTransforms: '*'
    contentColumnType: text
    fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb
  5e76b2e3-1eae-4bbc-93f4-122fe4526b02:
    name: Summary
    handle: summary
    instructions: 'Summary for the blog index'
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\redactor\Field
    settings:
      redactorConfig: ''
      purifierConfig: ''
      cleanupHtml: true
      removeInlineStyles: '1'
      removeEmptyTags: '1'
      removeNbsp: '1'
      purifyHtml: '1'
      columnType: text
      availableVolumes: ''
      availableTransforms: '*'
    contentColumnType: text
    fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb
  cdd377e5-a451-46b0-ae80-bc4cee907d3e:
    name: Caption
    handle: caption
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb
  db95de40-4dec-44cc-9d17-bba2223c91cf:
    name: 'Image Alt'
    handle: imageAlt
    instructions: 'Optional text for the `<img>` tag `alt` attribute.'
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb
  e567b6ab-3855-452b-a337-4c119dac4d62:
    name: 'Body Content'
    handle: bodyContent
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Matrix
    settings:
      minBlocks: ''
      maxBlocks: ''
      contentTable: '{{%matrixcontent_bodycontent}}'
      propagationMethod: all
    contentColumnType: string
    fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb
matrixBlockTypes:
  0c98f9b9-84bf-4766-af63-a3568b46c0a6:
    field: e567b6ab-3855-452b-a337-4c119dac4d62
    name: 'Rich Text'
    handle: richText
    sortOrder: 1
    fields:
      df3a27ff-e318-422f-8ff5-d626eda8ce54:
        name: 'Rich Text'
        handle: richText
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\redactor\Field
        settings:
          redactorConfig: Standard.json
          purifierConfig: ''
          cleanupHtml: true
          removeInlineStyles: '1'
          removeEmptyTags: '1'
          removeNbsp: '1'
          purifyHtml: '1'
          columnType: text
          availableVolumes: '*'
          availableTransforms: '*'
        contentColumnType: text
        fieldGroup: null
    fieldLayouts:
      59ffc94b-a1a3-4ecb-98e4-67dbd4317f23:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              df3a27ff-e318-422f-8ff5-d626eda8ce54:
                required: false
                sortOrder: 1
  28d5c036-8cb0-4a14-b553-0167ee34efbe:
    field: e567b6ab-3855-452b-a337-4c119dac4d62
    name: Image
    handle: image
    sortOrder: 3
    fields:
      5d2372e2-c220-4af4-80c9-49bb8c85a92e:
        name: Position
        handle: position
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\Dropdown
        settings:
          optgroups: true
          options:
            -
              label: Wide
              value: wide
              default: '1'
            -
              label: Center
              value: center
              default: ''
            -
              label: Left
              value: left
              default: ''
            -
              label: Right
              value: right
              default: ''
        contentColumnType: string
        fieldGroup: null
      6b203fd7-eca1-4313-8795-efbb5f6a8e63:
        name: Image
        handle: image
        instructions: 'Double-click the image thumbnail to apply a caption to an image.'
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Assets
        settings:
          useSingleFolder: ''
          defaultUploadLocationSource: 'volume:101a70a1-d200-4629-91e5-3425a0937c0e'
          defaultUploadLocationSubpath: images
          singleUploadLocationSource: 'volume:101a70a1-d200-4629-91e5-3425a0937c0e'
          singleUploadLocationSubpath: ''
          restrictFiles: '1'
          allowedKinds:
            - image
          sources: '*'
          source: null
          targetSiteId: null
          viewMode: large
          limit: '1'
          selectionLabel: 'Add an image'
          localizeRelations: false
          validateRelatedElements: ''
        contentColumnType: string
        fieldGroup: null
    fieldLayouts:
      d0baa120-b528-4317-a11e-0a36f80501c3:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              5d2372e2-c220-4af4-80c9-49bb8c85a92e:
                required: false
                sortOrder: 2
              6b203fd7-eca1-4313-8795-efbb5f6a8e63:
                required: false
                sortOrder: 1
  7e401ee6-3575-42de-b3b4-cedae706f392:
    field: e567b6ab-3855-452b-a337-4c119dac4d62
    name: 'Image Carousel'
    handle: imageCarousel
    sortOrder: 4
    fields:
      2f6bf496-df01-42e0-9b77-a764f886813d:
        name: 'Aspect Ratio'
        handle: aspectRatio
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\Dropdown
        settings:
          optgroups: true
          options:
            -
              label: '16:9'
              value: '16:9'
              default: '1'
            -
              label: '4:3'
              value: '4:3'
              default: ''
            -
              label: '3:2'
              value: '3:2'
              default: ''
        contentColumnType: string
        fieldGroup: null
      a6f02aa5-ab37-46e2-bbd4-3b56930577d5:
        name: Images
        handle: images
        instructions: 'Double-click an image thumbnail to apply a caption to an image.'
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Assets
        settings:
          useSingleFolder: ''
          defaultUploadLocationSource: 'volume:101a70a1-d200-4629-91e5-3425a0937c0e'
          defaultUploadLocationSubpath: images
          singleUploadLocationSource: 'volume:101a70a1-d200-4629-91e5-3425a0937c0e'
          singleUploadLocationSubpath: ''
          restrictFiles: '1'
          allowedKinds:
            - image
          sources: '*'
          source: null
          targetSiteId: null
          viewMode: large
          limit: ''
          selectionLabel: 'Add an image'
          localizeRelations: false
          validateRelatedElements: ''
        contentColumnType: string
        fieldGroup: null
    fieldLayouts:
      a3b39778-708a-4de0-9501-6b1d37108919:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              2f6bf496-df01-42e0-9b77-a764f886813d:
                required: false
                sortOrder: 2
              a6f02aa5-ab37-46e2-bbd4-3b56930577d5:
                required: false
                sortOrder: 1
  a121b8e6-70e6-421b-9629-c664d2949934:
    field: e567b6ab-3855-452b-a337-4c119dac4d62
    name: Quote
    handle: quote
    sortOrder: 2
    fields:
      09c265f3-2ab1-405d-9111-108e6b54f0fb:
        name: Quote
        handle: quote
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\redactor\Field
        settings:
          redactorConfig: Simple.json
          purifierConfig: ''
          cleanupHtml: true
          removeInlineStyles: '1'
          removeEmptyTags: '1'
          removeNbsp: '1'
          purifyHtml: '1'
          columnType: text
          availableVolumes: '*'
          availableTransforms: '*'
        contentColumnType: text
        fieldGroup: null
      5fd465cf-5b00-4b4f-8ee0-ce0eac4fd2eb:
        name: Attribution
        handle: attribution
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: ''
          initialRows: '4'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
      a6ca7d80-fa7f-433b-b6ba-fd9f19791f82:
        name: Style
        handle: style
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\Dropdown
        settings:
          optgroups: true
          options:
            -
              label: Blockquote
              value: blockquote
              default: '1'
            -
              label: Pullquote
              value: pullquote
              default: ''
        contentColumnType: string
        fieldGroup: null
    fieldLayouts:
      e25f5116-982d-45a0-ac12-9d3a3f1d07e7:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              09c265f3-2ab1-405d-9111-108e6b54f0fb:
                required: false
                sortOrder: 2
              5fd465cf-5b00-4b4f-8ee0-ce0eac4fd2eb:
                required: false
                sortOrder: 3
              a6ca7d80-fa7f-433b-b6ba-fd9f19791f82:
                required: false
                sortOrder: 1
  fb2f8912-57ad-4b4e-887d-e55f22a6d348:
    field: e567b6ab-3855-452b-a337-4c119dac4d62
    name: Embed
    handle: embed
    sortOrder: 5
    fields:
      e8fdd2ad-6739-4bab-a689-8a422e18a8f4:
        name: Embed
        handle: embed
        instructions: ''
        searchable: false
        translationMethod: none
        translationKeyFormat: null
        type: wrav\oembed\fields\OembedField
        settings:
          url: ''
        contentColumnType: text
        fieldGroup: null
    fieldLayouts:
      edfa3f3b-4e3a-4aa8-959c-95de3a10409d:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              e8fdd2ad-6739-4bab-a689-8a422e18a8f4:
                required: true
                sortOrder: 1
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  oembed:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      enableCache: '1'
sections:
  4593234a-cdd0-4c54-9931-4eb606b9e7f5:
    name: Home
    handle: home
    type: single
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      f3400d6f-0f33-4cef-9521-f8f6620399ec:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: _private/home
    entryTypes:
      8518a799-a012-4a6c-aa89-6a347cc00c2e:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: ''
        titleFormat: '{section.name|raw}'
        sortOrder: 1
        fieldLayouts:
          434b8bff-3f8f-4c04-b4e1-43001b019d73:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  031e8547-9981-4367-ad27-178240517ea1:
                    required: false
                    sortOrder: 1
  5a80053a-6435-4fd2-8a47-53e409d994ad:
    name: About
    handle: about
    type: single
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      f3400d6f-0f33-4cef-9521-f8f6620399ec:
        enabledByDefault: true
        hasUrls: true
        uriFormat: about
        template: _private/about
    entryTypes:
      dbd1be32-5e0d-4483-92a5-cc47aba67dcc:
        name: About
        handle: about
        hasTitleField: false
        titleLabel: ''
        titleFormat: '{section.name|raw}'
        sortOrder: 1
        fieldLayouts:
          0476a59c-d8e9-40fd-bce3-4ba321daf851:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  e567b6ab-3855-452b-a337-4c119dac4d62:
                    required: false
                    sortOrder: 1
  db2dff45-19b4-479c-8cba-ab88e7e7d2fd:
    name: Blog
    handle: blog
    type: channel
    enableVersioning: true
    siteSettings:
      f3400d6f-0f33-4cef-9521-f8f6620399ec:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'blog/{slug}'
        template: _private/blog-entry
    entryTypes:
      bb6d289b-c3cf-4a8d-9324-b98cbd32753b:
        name: Blog
        handle: blog
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          abfbb4c4-848b-4bbb-a8ab-fa5edb8941b6:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  5e76b2e3-1eae-4bbc-93f4-122fe4526b02:
                    required: false
                    sortOrder: 1
                  e567b6ab-3855-452b-a337-4c119dac4d62:
                    required: false
                    sortOrder: 2
    propagationMethod: all
siteGroups:
  90dee5cc-23f1-40ac-ae14-3fa71bebc4dc:
    name: 'Craft Blog'
sites:
  f3400d6f-0f33-4cef-9521-f8f6620399ec:
    siteGroup: 90dee5cc-23f1-40ac-ae14-3fa71bebc4dc
    name: 'Craft Blog'
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: $DEFAULT_SITE_URL
    sortOrder: 1
    primary: true
system:
  edition: solo
  name: 'Craft Blog'
  live: true
  schemaVersion: 3.3.3
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  101a70a1-d200-4629-91e5-3425a0937c0e:
    name: Uploads
    handle: uploads
    type: craft\volumes\Local
    hasUrls: true
    url: '@web/uploads'
    settings:
      path: '@webroot/uploads'
    sortOrder: 1
    fieldLayouts:
      f6203211-ad03-49ec-8423-3d215898f508:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              cdd377e5-a451-46b0-ae80-bc4cee907d3e:
                required: false
                sortOrder: 1
              db95de40-4dec-44cc-9d17-bba2223c91cf:
                required: false
                sortOrder: 2
